### ISSUE TITLE
[DOCS]: Set up a CONTRIBUTING file

### ISSUE THREAD

**Issue by Vyvy-vi** [Vyvy-vi/TEC-Discord-Oauth2#19]
## Expected information

This repository should have a `CONTRIBUTING.md` file.

## Additional information

It would be recommended to **NOT** copy the contributing file from existing big projects, since the files there are meant for the purpose of that particular repo. You could add the contributing file from one of [Vyvy-vi's](https://github.com/Vyvy-vi) repos-
https://github.com/Vyvy-vi/new-repo-template/blob/main/CONTRIBUTING.md

for more info on contributing files-
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by slayer321** [comment]
Hey @Vyvy-vi, I will like to take this issue.

**Comment by Vyvy-vi** [comment]
Go on @slayer321 !
