### ISSUE TITLE
[DOCS] : Set up a CODE_OF_CONDUCT file 

### ISSUE THREAD

**Issue by slayer321** [Vyvy-vi/TEC-Discord-Oauth2#20]
Code of conduct file needs to add to this project.

**Comment by slayer321** [comment]
As I'm setting up the Contributing file, I thought that this project also doesn't have a Code of conduct file that also needs to be added.  So I will like to take this issue.

**Comment by Vyvy-vi** [comment]
I would appreciate if both are added in separate PRs.
For the COC, you could use the - Contributor Covenant template from github
